### ISSUE TITLE
face_recognition_HAAR.py doesnot create any aligned_3D images

### ISSUE THREAD

**Issue by HananAhmadHunain** [appstud/3DFaceRecognitionOnRaspberryPI#1]
I am using raspberry pi USB webcam, and recording a 20sec .avi video into database folder.
when i run face_recognition_HAAR it says finished after few seconds but there are no files inside database_aligned_3D folder

**Comment by Fawzikhattar** [comment]
Hello, the code was tested using Raspberri pi module camera not USB. What might change are the camera intrinsic parameters that are hardcoded. You can try to pass "2D" instead of "3D" as a parameter to the readVideoAndLabels function. If this works and you want to use the 3D alignment consider calibrating your camera and changing the camera intrinsics in the code. Let me know if you need further help.

**Comment by HananAhmadHunain** [comment]
Thank you for your reply, But changing 3D to 2D has not resolved the issue.
Do you have any tips for the video? Should i move my head around? Length of video? how many frames in the video? 
BTW there aren't any errors even the video is streaming to the web browser. but the folder that should have aligned photos is empty.
In my opinion face_recognition_HAAR is unable to recognize face from the video or something like that.
Can you give me any thoughts on where the problem might be so i can deeply analyze that part? 
Thankyou in advance

**Comment by Fawzikhattar** [comment]
In this case the face detector failed. Try to record another video with different conditions especially the distance to the camera). I used HAAR cascade to get fast detections with these parameters minSize=(50,50),maxSize=(55,55). That said you can also try to change these parameters to allow face detection with different face size but you will loose some speed for inference after.

**Comment by YINXP** [comment]
Hello, I also have the same issue, even after I changed the maxSize to (120, 120),  There was nothing inside database_aligned_3D.
BTW, When I passed 2D as a parameter , I got another issue "performFaceAlignment not defined"

**Comment by Fawzikhattar** [comment]
Can you check the latest commit and tell me what logs do you have in case you still have problems?
