### ISSUE TITLE
Changing values to make it work with a standard USB Camera

### ISSUE THREAD

**Issue by Fischchen** [appstud/3DFaceRecognitionOnRaspberryPI#2]
Hey,

I'm trying to get this to work reliably with a USB Camera, it works now after I changed all references of Picamera to CV2, however it's a bit unreliable. Are there any values I can change to make it more reliable?

Thanks in advance,
Fischchen

**Comment by Fawzikhattar** [comment]
If you changed the camera you will need to do the calibration to estimate the intrinsic matrix and the distortion coefficients. You will then need to replace these parameters in the frontalize.py and main.py files:
 
self.out_A=np.asmatrix(np.array([[291.0,0,158.0],[0,291.0,117.0],[0,0,1]]))
  self.distCoeff=np.array([0.03885,-0.2265,0.005354,-0.0016,0.1353])

If you don't do that the frontalisation will not work. If you have never done this before take a look at this:

https://learnopencv.com/camera-calibration-using-opencv/

Also to have the best results for the recognition it is recommended to build the database of images in the same lighting conditions/environment that you intend to use the system after.
